// Export class names as an object for easier use
export const styles = {
  appContainer: 'app-container',
  container: 'container',
  header: 'header',
  nav: 'nav',
  logo: 'logo',
  navLinks: 'nav-links',
  navLink: 'nav-link',
  navLinkActive: 'nav-link-active',
  mainContent: 'main-content',
  page: 'page',
  pageH1: 'page-h1',
  pageH2: 'page-h2',
  pageH3: 'page-h3',
  pageP: 'page-p',
  pageUl: 'page-ul',
  pageLi: 'page-li',
  pagePre: 'page-pre',
  pageCode: 'page-code',
  hero: 'hero',
  heroTitle: 'hero-title',
  subtitle: 'subtitle',
  features: 'features',
  feature: 'feature',
  featureH3: 'feature-h3',
  section: 'section',
  footer: 'footer',
  tabs: 'tabs',
  tab: 'tab',
  tabActive: 'tab-active',
  tabContent: 'tab-content'
};
